### ISSUE TITLE
Create release version 0.1.0

### ISSUE THREAD

**Issue by dhiller** [datanerds-io/verteiler#7]
We need a release version for incorporating into profile.

**Comment by larsp** [comment]
version `0.1.0` has been pushed to maven central staging (https://oss.sonatype.org/content/repositories/staging/)

https://oss.sonatype.org/content/repositories/staging/io/datanerds/verteiler/0.1.0/

Depending on your and @jckuester's feedback I would release it at some point.

Thanks
